### ISSUE TITLE
Fatal error in the log - Hacking attempt?

### ISSUE THREAD

**Issue by ElVasquito** [filegator/filegator#183]
Hello, I am receiving this fatal error in the log quite often:
'''
[2021-02-09 22:11:42] default.ALERT: Fatal Error (E_ERROR): Uncaught Exception: Csrf token not valid in [2021-02-09 22:11:42] default.ALERT: Fatal Error (E_ERROR): Uncaught Exception: Csrf token not valid in /var/www/mainsite/backend/Services/Security/Security.php:46 Stack trace: #0 /var/www/mainsite/backend/App.php(33): Filegator\Services\Security\Security->init(Array) #1 /var/www/mainsite/dist/index.php(53): Filegator\App->__construct(Object(Filegator\Config\Config), Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Kernel\StreamedResponse), Object(Filegator\Container\Container)) #2 {main}   thrown {"code":1,"message":"Uncaught Exception: Csrf token not valid in /var/www/mainsite/backend/Services/Security/Security.php:46\nStack trace:\n#0 /var/www/mainsite/backend/App.php(33): Filegator\\Services\\Security\\Security->init(Array)\n#1 /var/www/mainsite/dist/index.php(53): Filegator\\App->__construct(Object(Filegator\\Config\\Config), Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response), Object(Filegator\\Kernel\\StreamedResponse), Object(Filegator\\Container\\Container))\n#2 {main}\n  thrown","file":"/var/www/mainsite/backend/Services/Security/Security.php","line":46,"trace":null} []
'''
Is this a hacking attempt? Something to worry about? TIA

**Comment by alcalbg** [comment]
Visiting the site with cookies disabled can cause this kind of errors. Also, someone might be probing, scanning or scraping your website. I see this all the time on my websites.

**Comment by ElVasquito** [comment]
I see, OK then. Although the logs are getting quite big with this long error each time. Indeed the scanning/scraping. Thank you.

**Comment by alcalbg** [comment]
I totally agree, this is really huge. The next version will show this as a single line in the log.

Thanks!

**Comment by ElVasquito** [comment]
That's great, thank you once again!
