### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by llars0689** [filegator/filegator#199]
**Describe the bug**
When i enable the LDAP syntax to search for users in two different groups. It works, and lets the respective users login. But, if an admin LDAP user logs in, when you press "Users" it pops up showing "Unknown Error". Its not a deal breaker, as all users who are part of the respective groups can login. But Admins cant see an overview of the users who have access.

**To Reproduce**
1. Edit configuration.php
2. Add the LDAP adapter
3. Add the ldap filter syntax: ****'ldap_filter'=> '(&(|(memberOf=CN=TESTGROUP1,OU=TESTOU,DC=TEST,DC=com)(memberOf=CN=TESTGROUP2,OU=TESTOU,DC=TEST,DC=com)))',**
4. Once you save and try logging in with a respective user account, click "Users" and it will show the "Unknown Error"

**Expected behavior**
I would expect it to list all the users who are part of those two groups and show their permissions.

**Logs**
[2021-03-17 16:45:35] default.INFO: Logged in xxxx from IP xxxxxxxx

[2021-03-17 16:45:37] default.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: Argument 1 passed to Filegator\Services\Auth\User::setUsername() must be of the type string, null given, called in /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php on line 151 and defined in /var/www/filegator/backend/Services/Auth/User.php:85 Stack trace: #0 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(151): Filegator\Services\Auth\User->setUsername(NULL) #1 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(142): Filegator\Services\Auth\Adapters\LDAP->mapToUserObject(Array) #2 /var/www/filegator/backend/Controllers/AdminController.php(34): Filegator\Services\Auth\Adapters\LDAP->allUsers() #3 [internal function]: Filegator\Controllers\AdminController->listUsers(Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response)) #4 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array) #5 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call(Array, Array) #6 /var/www/filegator/backend {"code":1,"message":"Uncaught TypeError: Argument 1 passed to Filegator\\Services\\Auth\\User::setUsername() must be of the type string, null given, called in /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php on line 151 and defined in /var/www/filegator/backend/Services/Auth/User.php:85\nStack trace:\n#0 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(151): Filegator\\Services\\Auth\\User->setUsername(NULL)\n#1 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(142): Filegator\\Services\\Auth\\Adapters\\LDAP->mapToUserObject(Array)\n#2 /var/www/filegator/backend/Controllers/AdminController.php(34): Filegator\\Services\\Auth\\Adapters\\LDAP->allUsers()\n#3 [internal function]: Filegator\\Controllers\\AdminController->listUsers(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response))\n#4 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)\n#5 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\\Invoker->call(Array, Array)\n#6 /var/www/filegator/backend","file":"/var/www/filegator/backend/Services/Auth/User.php","line":85,"trace":null} []

**Environment (please complete the following information):**
 - FileGator Version 7.5.0
 - Server: Ubuntu 18.04.1
 - PHP Version 7.2.24
 - Browser - Brave

**Comment by llars0689** [comment]
After re-reading the log, i found out what the issue was...

Not all of my AD accounts who were members of those groups, had "uid" set on their accounts. After i manually added the uid to each of their accounts, i no longer get the error.

**Comment by ahaenggli** [comment]
hey @llars0689 
can you try it written in lowercase?
ex.:
```php
'ldap_attributes' => ["samaccountname","uid","cn","dn"],
'ldap_userFieldMapping'=> [
                       'username' =>'samaccountname',
                       ....
```

if you are logged in as an admin-user (username must be in this config array: 
```php
 'ldap_userFieldMapping'=> [
                       ...
                       'admin_usernames' =>['admin', 'llars0689', ...], 
                       ...               
```
)
you are able to see every user with its permissions in the "Users" overview:
![grafik](https://user-images.githubusercontent.com/23347180/111900941-8b4e5b00-8a35-11eb-838f-4db5d3426e17.png)
the ldap entries are read-only, so you can't delete an user here or change any permissions.

**Comment by llars0689** [comment]
Hi ahaenggli,

Thanks for this, using lower-case worked!



> hey @llars0689
> can you try it written in lowercase?
> ex.:
> 
> ```
> 'ldap_attributes' => ["samaccountname","uid","cn","dn"],
> 'ldap_userFieldMapping'=> [
>                        'username' =>'samaccountname',
>                        ....
> ```
> 
> if you are logged in as an admin-user (username must be in this config array:
> 
> ```
>  'ldap_userFieldMapping'=> [
>                        ...
>                        'admin_usernames' =>['admin', 'llars0689', ...], 
>                        ...               
> ```
> 
> )
> you are able to see every user with its permissions in the "Users" overview:
> ![grafik](https://user-images.githubusercontent.com/23347180/111900941-8b4e5b00-8a35-11eb-838f-4db5d3426e17.png)
> the ldap entries are read-only, so you can't delete an user here or change any permissions.

**Comment by llars0689** [comment]
In addition, i also seem to be getting this message every now and then in the app logs.

[2021-03-18 13:06:02] default.WARNING: E_WARNING: ldap_bind(): Unable to bind to server: Invalid credentials {"code":2,"message":"ldap_bind(): Unable to bind to server: Invalid credentials","file":"/var/www/filegator/backend/Services/Auth/Adapters/LDAP.php","line":214} []


Although, i know for a fact that the credentials are valid, and they are also working too... Even after getting this error in the logs, i can add a new user to the respective LDAP group and it can login fine, so its definitely authenticating. The error doesn't seem to be causing any problems, but just wondering why this would be logged...
