### ISSUE TITLE
Batch Download Error

### ISSUE THREAD

**Issue by netspl0it** [filegator/filegator#209]
Unknown error.

The Logs give me the following:
`[2021-04-18 21:12:53] default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class 'ZipArchive' not found in /var/www/client-phoenix/vendor/league/flysystem-ziparchive/src/ZipArchiveAdapter.php:41 Stack trace: #0 /var/www/client-phoenix/backend/Services/Archiver/Adapters/ZipArchiver.php(47): League\Flysystem\ZipArchive\ZipArchiveAdapter->__construct() #1 /var/www/client-phoenix/backend/Controllers/DownloadController.php(123): Filegator\Services\Archiver\Adapters\ZipArchiver->createArchive() #2 [internal function]: Filegator\Controllers\DownloadController->batchDownloadCreate() #3 /var/www/client-phoenix/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array() #4 /var/www/client-phoenix/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call() #5 /var/www/client-phoenix/backend/Services/Router/Router.php(78): DI\Container->call() #6 /var/www/client-phoenix/backend/App.php(33): Filegator\Services\Router\Router->init() #7 /var/www/client-phoenix/dist/index.php(53): Filegator\App->__construct() #8 {main}   thrown {"code":1,"message":"Uncaught Error: Class 'ZipArchive' not found in /var/www/client-phoenix/vendor/league/flysystem-ziparchive/src/ZipArchiveAdapter.php:41\nStack trace:\n#0 /var/www/client-phoenix/backend/Services/Archiver/Adapters/ZipArchiver.php(47): League\\Flysystem\\ZipArchive\\ZipArchiveAdapter->__construct()\n#1 /var/www/client-phoenix/backend/Controllers/DownloadController.php(123): Filegator\\Services\\Archiver\\Adapters\\ZipArchiver->createArchive()\n#2 [internal function]: Filegator\\Controllers\\DownloadController->batchDownloadCreate()\n#3 /var/www/client-phoenix/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()\n#4 /var/www/client-phoenix/vendor/php-di/php-di/src/Container.php(276): Invoker\\Invoker->call()\n#5 /var/www/client-phoenix/backend/Services/Router/Router.php(78): DI\\Container->call()\n#6 /var/www/client-phoenix/backend/App.php(33): Filegator\\Services\\Router\\Router->init()\n#7 /var/www/client-phoenix/dist/index.php(53): Filegator\\App->__construct()\n#8 {main}\n  thrown","file":"/var/www/client-phoenix/vendor/league/flysystem-ziparchive/src/ZipArchiveAdapter.php","line":41,"trace":null} []`

Please help! Thanks!

**Comment by netspl0it** [comment]
My server was misconfigured, sorry!
