### ISSUE TITLE
Bug report: Zipping

### ISSUE THREAD

**Issue by tobiasgruber1995** [filegator/filegator#236]
**Describe the bug**

When trying to zip a specific folder I get the error noted in the logs below. On other folders it works fine, so I assume it must have something to do with the folder I'm trying to zip, but I can not figure out what it is? Did you encounter that problem before or have an idea what might cause it?

**Expected behavior**

Zipping the folder as it works on other folders.

**Logs**

```
default.ALERT: Fatal Error (E_ERROR): Uncaught League\Flysystem\FileNotFoundException: File not found at path:  in /path/to/filegator/vendor/league/flysystem/src/Filesystem.php:390 Stack trace: #0 /path/to/filegator/vendor/league/flysystem/src/Filesystem.php(329): League\Flysystem\Filesystem->assertPresent('') #1 /path/to/filegator/backend/Services/Storage/Filesystem.php(68): League\Flysystem\Filesystem->getSize('') #2 /path/to/filegator/backend/Services/Storage/Filesystem.php(128): Filegator\Services\Storage\Filesystem->isDir('/') #3 /path/to/filegator/backend/Services/Archiver/Adapters/ZipArchiver.php(74): Filegator\Services\Storage\Filesystem->readStream('/path/to/file') #4 /path/to/filegator/backend/Services/Archiver/Adapters/ZipArchiver.php(65): Filegator\Services\Archiver\Adapters\ZipArchiver->addFileFromStorage('/path/to/file') #5 /path/to/filegator/backend/Controllers/FileController.php(125): Filegator\Services\Archiver\Adapt {"code":1,"message":"Uncaught League\\Flysystem\\FileNotFoundException: File not found at path:  in /path/to/filegator/vendor/league/flysystem/src/Filesystem.php:390\nStack trace:\n#0 /path/to/filegator/vendor/league/flysystem/src/Filesystem.php(329): League\\Flysystem\\Filesystem->assertPresent('')\n#1 /path/to/filegator/backend/Services/Storage/Filesystem.php(68): League\\Flysystem\\Filesystem->getSize('')\n#2 /path/to/filegator/backend/Services/Storage/Filesystem.php(128): Filegator\\Services\\Storage\\Filesystem->isDir('/')\n#3 /path/to/filegator/backend/Services/Archiver/Adapters/ZipArchiver.php(74): Filegator\\Services\\Storage\\Filesystem->readStream('/path/to/file')\n#4 /path/to/filegator/backend/Services/Archiver/Adapters/ZipArchiver.php(65): Filegator\\Services\\Archiver\\Adapters\\ZipArchiver->addFileFromStorage('/path/to/file')\n#5 /path/to/filegator/backend/Controllers/FileController.php(125): Filegator\\Services\\Archiver\\Adapt","file":"/path/to/filegator/vendor/league/flysystem/src/Filesystem.php","line":390,"trace":null} []
```

**Environment**

 - FileGator Version: 7.5.2
 - Server: Apache 2.4.41 on Debian Linux
 - PHP Version: PHP 7.4
 - Browser: Chrome, Firefox

**Comment by alcalbg** [comment]
Merge with #237
