### ISSUE TITLE
I'm getting an error when i try to download anything zip related, i can download single files with the ... menu

### ISSUE THREAD

**Issue by biast12** [filegator/filegator#386]
**Describe the bug**
I'm getting an error when i try to download anything zip related, i can download single files with the ... menu

**To Reproduce**
1. Select a file
2. Click on 'Download'

**Expected behavior**
Download the files as a zip

**Logs**
[app.log](https://github.com/filegator/filegator/files/10819591/app.log)

**Screenshot**
![image](https://user-images.githubusercontent.com/53872542/221063916-54da0c2e-1c32-4dc8-a025-ae9ed09b074f.png)

**Error**
```
Uncaught Error: Class "ZipArchive" not found in G:\Onedrives\vendor\league\flysystem-ziparchive\src\ZipArchiveAdapter.php:41 Stack trace: #0 G:\Onedrives\backend\Services\Archiver\Adapters\ZipArchiver.php(47): League\Flysystem\ZipArchive\ZipArchiveAdapter->__construct('G:\\Onedrives/pr...') #1 G:\Onedrives\backend\Controllers\DownloadController.php(123): Filegator\Services\Archiver\Adapters\ZipArchiver->createArchive(Object(Filegator\Services\Storage\Filesystem)) #2 [internal function]: Filegator\Controllers\DownloadController->batchDownloadCreate(Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Services\Archiver\Adapters\ZipArchiver)) #3 G:\Onedrives\vendor\php-di\invoker\src\Invoker.php(82): call_user_func_array(Array, Array) #4 G:\Onedrives\vendor\php-di\php-di\src\Container.php(276): Invoker\Invoker->call(Array, Array) #5 G:\Onedrives\backend\Services\Router\Router.php(78): DI\Container->call(Array, Array) #6 G:\Onedrives\backend\App.php(33): Filegator\Services\Router\Router->init(Array) #7 G:\Onedrives\dist\index.php(55): Filegator\App->__construct(Object(Filegator\Config\Config), Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Kernel\StreamedResponse), Object(Filegator\Container\Container)) #8 {main}   thrown {"code":1,"message":"Uncaught Error: Class \"ZipArchive\" not found in G:\\Onedrives\\vendor\\league\\flysystem-ziparchive\\src\\ZipArchiveAdapter.php:41\nStack trace:\n#0 G:\\Onedrives\\backend\\Services\\Archiver\\Adapters\\ZipArchiver.php(47): League\\Flysystem\\ZipArchive\\ZipArchiveAdapter->__construct('G:\\\\Onedrives/pr...')\n#1 G:\\Onedrives\\backend\\Controllers\\DownloadController.php(123): Filegator\\Services\\Archiver\\Adapters\\ZipArchiver->createArchive(Object(Filegator\\Services\\Storage\\Filesystem))\n#2 [internal function]: Filegator\\Controllers\\DownloadController->batchDownloadCreate(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response), Object(Filegator\\Services\\Archiver\\Adapters\\ZipArchiver))\n#3 G:\\Onedrives\\vendor\\php-di\\invoker\\src\\Invoker.php(82): call_user_func_array(Array, Array)\n#4 G:\\Onedrives\\vendor\\php-di\\php-di\\src\\Container.php(276): Invoker\\Invoker->call(Array, Array)\n#5 G:\\Onedrives\\backend\\Services\\Router\\Router.php(78): DI\\Container->call(Array, Array)\n#6 G:\\Onedrives\\backend\\App.php(33): Filegator\\Services\\Router\\Router->init(Array)\n#7 G:\\Onedrives\\dist\\index.php(55): Filegator\\App->__construct(Object(Filegator\\Config\\Config), Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response), Object(Filegator\\Kernel\\StreamedResponse), Object(Filegator\\Container\\Container))\n#8 {main}\n  thrown","file":"G:\\Onedrives\\vendor\\league\\flysystem-ziparchive\\src\\ZipArchiveAdapter.php","line":41,"trace":null} []
```

**Environment (please complete the following information):**
 - FileGator Version: 7.9.2 (with custom dir)
 - Server: php and ngrok
 - PHP Version: 8.2.0
 - Browser: opera

**Additional context**
not sure if this could be it, but i'm not using the default "filegator" folder

i can host a ngrok server when you guys are ready too so you can see the error live, i can also send the files to you if you wanna cross check code, maybe talking over Discord would be better for that tho (`Biast12 (Tobias)#0001`)

**Comment by biast12** [comment]
Nvm i found the issue lol, forgot to turn on the zip extention
