### ISSUE TITLE
Unknown error while trying to open a certain folder

### ISSUE THREAD

**Issue by AlanPszenyckyj** [filegator/filegator#394]
**Describe the bug**
Hi! I have a problem trying to access a certain folder from my repository. I modified the code to change the colors, add the icons from my company but the main code remains the same. I have built the image using Docker on a Debian 11 virtual machine, mapping the repository and private folders to a drive with all permisions. Everything else works as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/99336787/230108839-ad078a1f-9123-40dc-a435-4294da6f2182.png)

**Logs**
[2023-04-05 12:38:20] default.ALERT: Fatal Error (E_ERROR): Uncaught UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in /var/www/filegator/vendor/symfony/http-foundation/Response.php:406 Stack trace: #0 /var/www/filegator/backend/Kernel/Response.php(23): Symfony\Component\HttpFoundation\Response->setContent(false) #1 /var/www/filegator/backend/Controllers/FileController.php(55): Filegator\Kernel\Response->json(Object(Filegator\Services\Storage\DirectoryCollection)) #2 [internal function]: Filegator\Controllers\FileController->changeDirectory(Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response)) #3 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array) #4 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call(Array, Array) #5 /var/www/filegator/backend/Services/Router/Router.php(78): DI\Container->call(Array, Array) #6 /var/www/filegator/backend/App.php(33): Filegator\Services\Router\Router->init(Array) #7 /var/ww {"code":1,"message":"Uncaught UnexpectedValueException: The Response content must be a string or object implementing __toString(), \"boolean\" given. in /var/www/filegator/vendor/symfony/http-foundation/Response.php:406\nStack trace:\n#0 /var/www/filegator/backend/Kernel/Response.php(23): Symfony\\Component\\HttpFoundation\\Response->setContent(false)\n#1 /var/www/filegator/backend/Controllers/FileController.php(55): Filegator\\Kernel\\Response->json(Object(Filegator\\Services\\Storage\\DirectoryCollection))\n#2 [internal function]: Filegator\\Controllers\\FileController->changeDirectory(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response))\n#3 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)\n#4 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\\Invoker->call(Array, Array)\n#5 /var/www/filegator/backend/Services/Router/Router.php(78): DI\\Container->call(Array, Array)\n#6 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Router\\Router->init(Array)\n#7 /var/ww","file":"/var/www/filegator/vendor/symfony/http-foundation/Response.php","line":406,"trace":null} []

**Environment (please complete the following information):**
 - FileGator Version 7.9.2
 - Server: Docker Debian 11
 - PHP Version [e.g. PHP 7.3]

**Comment by AlanPszenyckyj** [comment]
Problem Solved, there was a .exe which name contained the word "Español", Linux took it as Espa'$'\361'ol and the web crashed trying to retrieve the folders content. So Filegator doesnt support names with the character Ñ
