### ISSUE TITLE
Can not build the project

### ISSUE THREAD

**Issue by geograman** [filegator/filegator#414]
### **Hi, if I try to build the project I first get this error**

Error: Node Sass version 9.0.0 is incompatible with ^4.0.0.

### **after solving that I get:** 

`⠇  Building for production...

 ERROR  Failed to compile with 3 errors                                                                                                                                  11:35:49 PM

[eslint] ESLint is not a constructor

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 error  in ./frontend/mixins/shared.js

Module not found: Error: Can't resolve 'moment' in '/var/www/html/filegator/frontend/mixins'

  Error: Child compilation failed:
  [eslint] ESLint is not a constructor

  - child-compiler.js:169
    [filegator]/[cli-service]/[html-webpack-plugin]/lib/child-compiler.js:169:18

  - Compiler.js:551 finalCallback
    [filegator]/[cli-service]/[webpack]/lib/Compiler.js:551:5

  - Compiler.js:577
    [filegator]/[cli-service]/[webpack]/lib/Compiler.js:577:11

  - Compiler.js:1200
    [filegator]/[cli-service]/[webpack]/lib/Compiler.js:1200:17

  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [filegator]/[cli-service]/[tapable]/lib/Hook.js:18:14

  - Compiler.js:1196
    [filegator]/[cli-service]/[webpack]/lib/Compiler.js:1196:33

  - Compilation.js:2795 finalCallback
    [filegator]/[cli-service]/[webpack]/lib/Compilation.js:2795:11

  - Compilation.js:3100
    [filegator]/[cli-service]/[webpack]/lib/Compilation.js:3100:11

  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [filegator]/[cli-service]/[tapable]/lib/Hook.js:18:14

  - Compilation.js:3093
    [filegator]/[cli-service]/[webpack]/lib/Compilation.js:3093:38

  - Compilation.js:522
    [filegator]/[cli-service]/[webpack]/lib/Compilation.js:522:10

  - SourceMapDevToolPlugin.js:585
    [filegator]/[cli-service]/[webpack]/lib/SourceMapDevToolPlugin.js:585:10

  - async.js:2830
    [filegator]/[neo-async]/async.js:2830:7

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /var/www/html/filegator/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:157:8
    at /var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Cache.js:150:23)
    at /var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:1222:23)
    at /var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:156:16
    at finalCallback (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:441:32)
    at /var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/var/www/html/filegator/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:456:21)`

**Comment by alcalbg** [comment]
Closed with #508

Try with node v16
