### ISSUE TITLE
LDAPS using self signed certificates

### ISSUE THREAD

**Issue by facorazza** [filegator/filegator#475]
Where should the CA certificate be loaded so that it is recognized by filegator?

I've tried:

- `/etc/ssl/certs/cacert.pem`
- `/etc/ssl/certs/ca-certificates.crt`

**Logs**

```
Fatal error: Uncaught Exception: Cannot Bind to LDAP server: Wrong credentials? in /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php:184 Stack trace: #0 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(129): Filegator\Services\Auth\Adapters\LDAP->getUsers() #1 /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php(140): Filegator\Services\Auth\Adapters\LDAP->find('guest') #2 /var/www/filegator/backend/Services/Router/Router.php(33): Filegator\Services\Auth\Adapters\LDAP->getGuest() #3 /var/www/filegator/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(143): Filegator\Services\Router\Router->__construct(Object(Filegator\Kernel\Request), Object(Filegator\Services\Auth\Adapters\LDAP), Object(Filegator\Container\Container)) #4 /var/www/filegator/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array) #5 /var/www/filegator/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array) #6 /var/www/filegator/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array) #7 /var/www/filegator/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition)) #8 /var/www/filegator/backend/App.php(32): DI\Container->get('\\Filegator\\Serv...') #9 /var/www/filegator/dist/index.php(50): Filegator\App->__construct(Object(Filegator\Config\Config), Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Kernel\StreamedResponse), Object(Filegator\Container\Container)) #10 {main} thrown in /var/www/filegator/backend/Services/Auth/Adapters/LDAP.php on line 184
```

**Environment (please complete the following information):**
 - FileGator stock Docker container 7.10.1
 
**Additional context**
When loading the certificate on `/etc/ssl/certs/ca-certificates.crt`, I'm able to verify the certificate for an S3 storage.

**Comment by facorazza** [comment]
That was it!
I ended up setting the env var LDAPTLS_CACERT with the path to the ca certificate
