### ISSUE TITLE
How can I using diffenent sessions for each sub dir in same domain?

### ISSUE THREAD

**Issue by vagra** [filegator/filegator#99]
I using filegator for multiple sub dirs in one domain, like:

//***.com/sub1/
//***.com/sub2/
//***.com/sub3/

when a user loged in at /sub1/, he loged in at all sub dirs, there will be some risks.

I want using different sessions for each sub dir, How can I set the configuration?

**Comment by vagra** [comment]
I change configuration.php:
```
'Filegator\Services\Session\SessionStorageInterface' => [
            'handler' => '\Filegator\Services\Session\Adapters\SessionStorage',
            'config' => [
                'handler' => function () {
                    $save_path = null; // use default system path
                    //$save_path = __DIR__.'/private/sessions';
                    $handler = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler($save_path);

                    return new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage([
                        // add these lines.
                        'name' => 'convert.kepan.org',
                        'session.cookie_domain' => '.kepan.org',
                        'session.cookie_path' => '/convert',
                        'session.cookie_secure' => false
                    ], $handler);
                },
            ],
        ],
```

but not effects.

then I change \backend\Services\Session\Adapters\SessionStorage.php
```
public function init(array $config = [])
    {
        // we don't have a previous session attached
        if (! $this->getSession()) {
            $handler = $config['handler'];
            $session = new Session($handler());
            // $session->setName('filegator');    // remove this line because it replace the 'name' setting.

            $this->setSession($session);
        }
    }
```

but it report error:
```
[26-May-2020 00:58:27 Asia/Shanghai] PHP Fatal error:  Uncaught Exception: Csrf token not valid in ...\backend\Services\Security\Security.php:46
Stack trace:
#0 ...\backend\App.php(33): Filegator\Services\Security\Security->init(Array)
#1 ...\dist\index.php(57): Filegator\App->__construct(Object(Filegator\Config\Config), Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Kernel\StreamedResponse), Object(Filegator\Container\Container))
#2 {main}
  thrown in ...\backend\Services\Security\Security.php on line 46
```
